version: '3.3'

services:

  movie-db:
    image: mysql:8.0.26
    container_name: movie-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'movie_trash'
      MYSQL_USER: 'movie_user'
      MYSQL_PASSWORD: 'movie_pass'
    ports:
      - '3306:3306'
    volumes:
      - movie-db:/var/lib/mysql
    networks:
      - movie-network

  movie-service:
    build: .
    image: 'movie-service:latest'
    container_name: movie-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    depends_on:
      - movie-db
    networks:
      - movie-network

networks:
  movie-network:


volumes:
  movie-db: { }
